---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: kube-system
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: sealed-secrets
  chart:
    git: ssh://git@github.com/l0ck3/experimental-clusters-library
    ref: master
    path: clusters-services/helm/sealed-secrets
  values: {}

